name: Update KML File
run-name: Update KML File

on:
  schedule:
    - cron: '55 19 * * *'
  workflow_dispatch:

jobs:
  update-kml:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip3 install requests
        
    - name: Run toKML.py
      run: python toKML.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add . && git commit -m "Auto-update KML file $(date)"
        git push origin Automatic
